Projects/Smart_Kart/FaceDetect/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('FaceDetection.urls')),
]

Projects/Smart_Kart/FaceDetection/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout' ),
    path('memolistview/', views.memolist_view, name='memolist_view'),
    path('update_memo/', views.update_memo, name='update_memo'),
    path('finishedlistview/', views.finishedlist_view, name='finishedlist_view'),
    path('add_memo/', views.add_memo, name='add_memo'),
    path('basketlist/', views.basketlist, name='basketlist'),
    path('ocr/', views.ocr, name='ocr'),
    path('delete_item/', views.delete_item, name='delete_item'),
    path('view_item/', views.view_item, name='view_item'),
    path('add_item/', views.add_item, name='add_item'),
    path('edit_item/', views.edit_item, name='edit_item'),
    path('update_item/', views.update_item, name='update_item'),
    path('finish-list-item/<id>/', views.finish_list_item, name='finish-list-item'),
    path('delete-list-item/<id>/', views.delete_list_item, name='delete-list-item'),
    path('recover-list-item/<id>/', views.recover_list_item, name='recover-list-item'),
    path('userpage/', views.userpage, name='userpage' ),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Projects/Smart_Kart/FaceDetection/models.py
from django.db import models

# Create your models here.
class ImageUploadModel(models.Model):
    #description = models.CharField(max_length=255, blank=True)
    document = models.ImageField(upload_to = 'images/%Y/%m/%d', verbose_name = '가격표')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    contents=models.CharField(max_length=500, blank=True)

from django.utils import timezone


class basket(models.Model):
    bsno = models.AutoField(primary_key=True)
    pdname = models.CharField(max_length=100)
    pdqty = models.IntegerField(default=1)
    pdprice=models.IntegerField()
    todo_id=models.IntegerField()
    done=models.IntegerField(default=1)


from django.db import models



class User(models.Model): #장고에서 제공하는 models.Model를 상속받아야한다.
    uemail = models.CharField(max_length=64,verbose_name = '사용자명')
    upw = models.CharField(max_length=128,verbose_name = '비밀번호')
    #registered_dttm = models.DateTimeField(auto_now_add=True,verbose_name='등록시간') 
    #저장되는 시점의 시간을 자동으로 삽입해준다.

    def __str__(self): # 이 함수 추가
        return self.uemail  # User object 대신 나타낼 문자 


    class Meta: #메타 클래스를 이용하여 테이블명 지정
        db_table = 'user'



LABLE_CHOICES = (
    ("primary", "기본"),
    ("success", "욕망의바구니"),
    ("danger", "중요"),
    ("warning", "기념일"),
    ("info", "회사"),
)

class memo(models.Model):
    mname = models.CharField(max_length=250, verbose_name="제목")
    cdate = models.DateField(default=timezone.now().strftime("%Y-%m-%d"), verbose_name="작성일")
    mdetail = models.TextField(max_length=1000, blank=True, verbose_name="내용")
    label = models.CharField(choices=LABLE_CHOICES, max_length=20, verbose_name="라벨")
    finished = models.BooleanField(default=False, verbose_name="계산완료")
    id = models.AutoField(primary_key=True)
    uemail = models.CharField(max_length=64,verbose_name = '사용자명')
    budget = models.IntegerField()
    class Meta:
        ordering = ["-cdate"]

Projects/Smart_Kart/FaceDetection/forms.py
from django import forms

class UploadImageForm(forms.Form):
    title = forms.CharField(max_length=50)
    image = forms.ImageField()

from .models import ImageUploadModel, basket, memo
from django_summernote.widgets import SummernoteWidget

class ImageUploadForm(forms.ModelForm):
    class Meta:
        model = ImageUploadModel
        fields = ('document',)

class basketForm(forms.ModelForm):
    class Meta:
        model = basket
        fields = ('pdname','pdprice')
        #help_text="제품명 수정"

class memoModelForm(forms.ModelForm):
    class Meta:
        model = memo
        fields = ('label',)

Projects/Smart_Kart/FaceDetection/views.py
# Create your views here.
#def first_view(request):
#  return render(request,'FaceDetection/first_view.html',{})
import re

from django.conf import settings
from .forms import ImageUploadForm
from .models import basket
from .opencv_dface import opencv_ocr
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.contrib.auth.hashers import make_password, check_password#비밀번호 암호와, 패스워드 체크(db에 있는 거와 일치성 확인)
from .models import User, memo
from django.contrib import messages

#추출 텍스트 전처리
def cleanText(ocrResult):
    pattern= '[a-zA-Z]'
    ocrResult = re.sub(pattern=pattern, repl='', string=ocrResult) #영어대소문자 제거
    pattern = '[^\w\s\.]'   
    ocrResult = re.sub(pattern=pattern, repl='', string=ocrResult) #특수문자 제거(.제외)
    ocrResult=re.sub(' ','',ocrResult)
    ocrResult=ocrResult.rstrip()
    print(ocrResult)
    return ocrResult


#전처리된 텍스트를 리스트로 변경
def strTolist(cleanResult):
    textlist=cleanResult.splitlines()
    textlist= ' '.join(textlist).split()
    return textlist

#가격 내에 .들어있으면 1순위로 pdprice, .안들어있으면 리스트 맨 뒤 값이 pdprice
def choose_pdprice(textlist):
    choose=re.compile('(.)*$')
    if choose.match(textlist):
        return textlist[1]
    else:
        textlist[-1]

#가격 구분점 . 제거
def strToNum(text):
    text = text.replace('.','')
    text = int(text)
    return text


def ocr(request):
    todo_id=request.GET.get('todo_id')    
    uemail=request.session.get('uemail')

    if request.method =='POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()

            imageURL = settings.MEDIA_URL + form.instance.document.name
            ocrResult = opencv_ocr(settings.MEDIA_ROOT_URL + imageURL)
            print(ocrResult)
            # 추출 텍스트 전처리
            cleanResult=cleanText(ocrResult)
            print('cleanResult:',cleanResult)
            # int, str 조건 설정
            #cleanResult=int_limit(cleanResult)
            #cleanResult=str_limit(cleanResult)
            # 전처리 텍스트 리스트화
            textlist=strTolist(cleanResult)
            print('textlist',textlist)
            # textlist=int_limit(textlist)
            # print('int_limit:',textlist)

            # 제품명, 가격 추출
            pdname=textlist[0]
            # pdprice=strToNum(textlist[1]) #-1
            pdprice=textlist[-1]
            if len(pdprice)>7:
                pdprice=textlist[-2]
            #strToTxt('20201029', ocrResult) #save_to_file
            print(pdname, pdprice)


            return render(request, 'FaceDetection/ocr.html',{'form':form,'uemail':uemail, 'post':post,'cleanResult':cleanResult, 'pdname':pdname, 'pdprice':pdprice,'todo_id':todo_id}) #'ocrResult':ocrResult,
    else:
        print('-----', request.GET.get('pdname'),request.GET.get('pdprice'))
        form = ImageUploadForm()
    return render(request, 'FaceDetection/ocr.html',{'form':form, 'todo_id':todo_id,'uemail':uemail})

def add_item(request):
    if request.method=='POST':

        # 1.  입력값을 확인한다
        pdname=request.POST.get('pdname')
        pdprice=request.POST.get('pdprice')
        pdprice=strToNum(pdprice)
        todo_id=request.POST.get('todo_id')
        # 2. 입력값을 저장한다
        bask=basket(pdname=pdname, pdprice=pdprice, todo_id=todo_id) #pdqty
        bask.save()

    return basketlist(request)

def get_total_price(self): #장본 항목 수량*가격 총 계산
    return sum(basket['pdqty']*basket['pdprice'] for basket in self.values())

def basketlist(request):
    uemail=request.session.get('uemail')
    #basket = basket.objects.all()
    # 3. 장바구니 리스트를 보여준다
    # 3.1 DB에 있는 장바구니 리스트를 호출 - select
    #3.2 form에 담아서 전달한다
    if request.method=='POST':
        todo_id=request.POST.get('todo_id')
    else:
        todo_id=request.GET.get('todo_id')

    #memolist 정보 가져오기
    memoset=memo.objects.all()
    memo_item=memoset.get(id=todo_id)
    mdetail = memo_item.mdetail
    mdetail = mdetail.split('\r\n')
    budget=memo_item.budget
    print('memo_item:',memo_item.mname)


    queryset =basket.objects.all()
    #bask_list=queryset .filter(todo_id=todo_id, done=0) #done=0 : 장볼 항목
    done_list=queryset .filter(todo_id=todo_id) #done=1 : 장본 항목
    print('basketlist todo_id : ', todo_id)
    total=get_total_price(done_list)
    

    context={'done_list':done_list,'total':total, 'todo_id':todo_id, 'mdetail':mdetail, 'memo_item':memo_item,
        "uemail":request.session.get('uemail')}
    
    if total > budget:
        # messages.info(request, '예산을 초과하였습니다!')
        messages.add_message(request,messages.INFO,'예산을 초과하였습니다!')
     
    return render(request, 'FaceDetection/basketlist.html', context)
       
     

def delete_item(request):
    bsno=request.GET.get('bsno')
    item=basket.objects.get(bsno=bsno)
    item.delete()   

    return redirect('/basketlist?todo_id='+request.GET.get('todo_id'))    


def view_item(request):
    uemail=request.session.get('uemail')
    bsno=request.GET.get('bsno')
    item=basket.objects.get(bsno=bsno)
    
    context={'item':item, 'uemail':uemail}
    return render(request, 'FaceDetection/view_item.html', context)

def edit_item(request):
    uemail=request.session.get('uemail')
    bsno=request.GET.get('bsno')
    item=basket.objects.get(bsno=bsno)

    context={'item':item, 'uemail':uemail}
    return render(request, 'FaceDetection/edit_item.html', context)

def update_item(request):
    uemail=request.session.get('uemail')

    if request.method=='POST':
        bsno=request.POST.get('bsno')
        item=basket.objects.get(bsno=bsno)        
        item.pdname=request.POST.get('pdname')
        item.pdprice=request.POST.get('pdprice')
        item.pdqty=request.POST.get('pdqty')
        # 2. 입력값을 저장한다
        item.save()
        print('1111111111111')

   
        item=basket.objects.get(bsno=bsno)
        context={'item':item, 'uemail':uemail}
    return render(request, 'FaceDetection/view_item.html', context)

def update_memo(request):
    uemail=request.session.get('uemail')

    if request.method=='POST':
        id=request.POST.get('id')
        edit_memo=memo.objects.get(id=id)
        edit_memo.mname=request.POST.get('mname')      
        edit_memo.mdetail=request.POST.get('mdetail')
        edit_memo.budget=request.POST.get('budget')
        edit_memo.label=request.POST.get('label')
        # 2. 입력값을 저장한다
        edit_memo.save()
        print('1111111111111')

   
    edit_memo=memo.objects.get(id=id)
    context={'edit_memo':edit_memo, 'uemail':uemail}
    return render(request, 'FaceDetection/edit_memo.html', context)


def signup(request):   #회원가입 페이지를 보여주기 위한 함수
    res_data = {} 
    if request.method == "GET":
        return render(request, 'FaceDetection/signup.html')

    elif request.method == "POST":
        username = request.POST.get('uemail',None)   #딕셔너리형태 (오류남.)
        password = request.POST.get('upw',None)
        re_password = request.POST.get('upw2',None)
        
        if not (username and password and re_password):
            res_data['error'] = "모든 값을 입력해야 합니다."
            return render(request, 'FaceDetection/signup.html', res_data)
        if password != re_password :
            res_data['error'] = '비밀번호가 다릅니다.'
            return render(request, 'FaceDetection/signup.html', res_data)
        else:
            user = User(uemail = username, upw=make_password(password))
            # res_data['error'] = "회원가입 성공"
            user.save()
    return render(request, 'FaceDetection/signup_complete.html', res_data) #signup을 요청받으면 signup.html 로 응답.

def login(request):
    response_data = {}

    if request.method == "GET" :
        return render(request, 'FaceDetection/login.html')

    elif request.method == "POST":
        login_username = request.POST.get('uemail', None)
        login_password = request.POST.get('upw', None)

        if not (login_username and login_password):
            response_data['error']="아이디와 비밀번호를 모두 입력해주세요."
        # if login_username != login_password:
        #     response_data['error']="회원가입이 필요한 서비스입니다." 
        
        else : 
            myuser = User.objects.get(uemail=login_username) 
            #db에서 꺼내는 명령. Post로 받아온 uemail로 , db의 uemail을 꺼내온다.
            if check_password(login_password, myuser.upw):
                request.session['user'] = myuser.id 
                request.session['uemail'] = myuser.uemail
                #세션도 딕셔너리 변수 사용과 똑같이 사용하면 된다.
                #세션 user라는 key에 방금 로그인한 id를 저장한것.
                return redirect('memolistview/')
            else:
                response_data['error'] = "비밀번호를 틀렸습니다."

        return render(request, 'FaceDetection/login.html',response_data)

  
def logout(request):
    request.session.pop('uemail')
    return redirect('/')

def userpage(request):
    uemail=request.session.get('uemail')
    context={
        "uemail":request.session.get('uemail'),}
    return render(request, 'FaceDetection/userpage.html', context) 

from .forms import memoModelForm
def add_memo(request):
    form = memoModelForm(request.POST)
    if request.method =="POST":
        mname=request.POST.get('mname')
        mdetail=request.POST.get('mdetail')
        uemail=request.session.get('uemail')
        label=request.POST.get('label')
        budget=request.POST.get('budget')

        # 2. 입력값을 저장한다
        instance_memo=memo.objects.create( mname=mname, mdetail=mdetail, label=label, budget=budget, uemail=uemail, finished=False) #pdqty
        instance_memo.save()
    return redirect('memolist_view')


# 장볼 목록 페이지
def memolist_view(request):
    form = memoModelForm(request.POST)
    memo_list = memo.objects.filter(finished=False, uemail=request.session.get('uemail'))
    context = {
        "memo_list": memo_list,    
        "uemail":request.session.get('uemail'),
        "form": form
    }
    return render(request, "FaceDetection/memo_list.html", context)


def finishedlist_view(request):
    uemail=request.session.get('uemail')

Projects/Smart_Kart/FaceDetection/templates/FaceDetection/basketlist.html
{% extends "base.html" %}
{%block content%}

<style>
h6 {
    position: relative;
}

.icons {
    position: absolute;
    right: 5px
}

.message {
  list-style:none;
  background-color:#4ec5a5;
  color:white;
  box-shadow: 12px 12px 12px #ffd54f;
  text-align: center;
  font-size: 30px;
}

</style>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>basket list</title>
</head>
<body>
    <h1>장바구니 리스트</h1>
    
<a href ="/ocr?todo_id={{todo_id}}"  class="btn btn-white ml-2">카메라</a><br><br>

<h3 style="text-align: left;">쇼핑 계획</h3>

<table class="table table-bordered">
  <tbody>
    <tr>
      <th scope="row">작성일</th>
      <td>{{memo_item.cdate}}</td>
      <th scope="row">목적</th>
      <td>{{memo_item.get_label_display}}</td>
    </tr>
    <tr>
      <th scope="row">제목</th>
      <td>{{memo_item.mname}}</td>
      <th scope="row">예산</th>
      <td>{{memo_item.budget}}</td>
      
    </tr>
    <tr>
      <th scope="row">내용</th>
      <td colspan="3">
        {%for detailitem in mdetail %}
        <li style = list-style:none;>{{detailitem}}</li>
        {% endfor %}
      </td>
    </tr>
    </tbody>
</table>

<br><br><br>
<form method='post' action='/last_basketlist/'>
<h3 style="text-align: left;">장바구니</h3>

{% if messages %}
<ul class='message'>
	{% for message in messages %}
		<li{% if message.tags %} class="{{message.tag}}"{%endif%}>
		{{ message}}</li>
	{% endfor %}
</ul>
{% endif %}

{% if done_list %}
    <table class="table table-hover">
        <thead>
          <tr>
            {% comment %} <th scope="col">#</th> {% endcomment %}
            <th scope="col">제품명</th>
            <th scope="col">수량</th>
            <th scope="col">가격</th>
          </tr>
        </thead>
        
        <tbody>
            {% for done in done_list %}
          <p><input name= 'done.bsno' type='hidden' value={{ done.bsno }}></p>
          <tr>
            
            {% comment %} <th scope="col" >{{ done.bsno}}</th> {% endcomment %}
            <td><a href='/view_item?bsno={{done.bsno}}&todo_id={{done.todo_id}}'>{{done.pdname }}</a></td>
            <td>{{done.pdqty }}</td>
            <td>{{done.pdprice}}</td>
            
          </tr>
          {% endfor %} 
        </tbody>
      </table>
    
    <p><input name= 'total' type='hidden' value={{ total }}></p>
{% endif %}

총계: {{total}}원<br>

 {% comment %} {% if messages %}
        {% for message in messages %}
         {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}

        {% endfor %}

    {% endif %} {% endcomment %}


</body>
</html>
{%endblock%}

Projects/Smart_Kart/FaceDetection/templates/FaceDetection/edit_item.html
{% extends "base.html" %}
{%block content%}

<style>
h6 {
    position: relative;
}

.icons {
    position: absolute;
    right: 5px
}

</style>

<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>basket list</title>
</head>
<body>
    <h1>수정</h1>
<form method='post' action='/update_item/'>
    {% csrf_token %}
    <table class="table table-bordered">
        <tbody>
            <tr>
                <th scope="row">번호</th>
                <td><input name='bsno' type='hidden' value={{item.bsno}}>{{item.bsno}}</td>
                      
            </tr>
          <tr>
            <th scope="row">수량</th>
            <td><input name='pdqty' value={{item.pdqty}}></td>
          </tr>
          <tr>
            <th scope="row">제품명</th>
            <td colspan="4"><input name='pdname' value={{item.pdname}}></td>            
          </tr>
          <tr>
            <th scope="row">가격</th>
            <td colspan="4"><input name='pdprice' value= {{item.pdprice}}></td>            
          </tr>
          </tbody>
          
      </table>
<button type='submit' class="btn btn-white ml-2">저장 </button>
    
</form>
 

</body>
</html>
{%endblock%}

Projects/Smart_Kart/FaceDetection/templates/FaceDetection/edit_memo.html
{% extends "base.html" %}
{%block content%}

<style>
h6 {
    position: relative;
}

.icons {
    position: absolute;
    right: 5px
}

</style>
<body>
    <h1>수정</h1>
<form method='post' action='/update_memo/'>
    {% csrf_token %}
    제목: <input name='mname' value={{edit_memo.mname}}><br>
    내용: <input name='mdetail' value= {{edit_memo.mdetail}}><br>
    예산: <input name='budget' value= {{edit_memo.budget}}><br>
    목적: <input name='label' value={{edit_memo.label}}><br>
    <button type='submit'>저장 </button>
</form>

<a href='/memolistview'>리스트</a>    

</body>
</html>
{%endblock%}

Projects/Smart_Kart/FaceDetection/templates/FaceDetection/finished_list.html
{% extends "base.html" %}
{%block content%}

<style>

h6 {
    position: relative;
}

.icons {
    position: absolute;
    right: 5px
}
    
</style>
    

<div class="container px-4 py-5 mx-auto">
    <div class="card card0">       
        
        <div class = "mt-1 mb-4"><h3>- 지난쇼핑목록 -</h3></div>
            
                {% for memo in finished_memo_list %}
                    <div class = 'card-body'>
                    <h6><a href="/basketlist?todo_id={{memo.id}}">{{memo.mname}}</a>
                        <span class = "badge badge-{{memo.label}}">
                        {{memo.get_label_display}}
                        </span><br>
                        {{memo.cdate}}
                            <span class="icons">
                                <a href="{% url 'recover-list-item' memo.id %}"><i class='fas fa-undo-alt'></i></a>&nbsp;           
                                <a href="{% url 'delete-list-item' memo.id %}"><i class='fas fa-trash' style="color:red;"></i></a>
                            </span>
                        </h6>
                            
                    </div>
                {% endfor %}
            
        </div>
        
    </div>
</div>
{%endblock%}

Projects/Smart_Kart/FaceDetection/templates/FaceDetection/login.html
{% extends "loginbase.html" %}
 {%block content%}
 <div class="container px-4 py-5 mx-auto">
     <div class="card card0">
         <div class="d-flex flex-lg-row flex-column-reverse">
             <div class="card card1">
                 <div class="row justify-content-center my-auto">
                     <div class="col-md-8 col-10 my-5">
                         <div class="row justify-content-center px-3 mb-3"><a href="{% url 'login'%}"><img id="logo" src="/static/css/img/cart.png" width = 300></a></div>
                         <h3 class="mb-5 text-center heading">Smart K-art</h3>
                         <h6 class="msg-info">Log-in</h6>
                         <form method = "POST">
                        {% csrf_token %}
                         <div class="form-group">
                             <label for="username" class="form-control-label text-muted">Username</label>
                             <input type="text" 
                             id="uemail" 
                             name="uemail" 
                             placeholder="이메일을 입력하세요" 
                             class="form-control"> 
                         </div>
                         <div class="form-group"> 
                             <label for="password" class="form-control-label text-muted">Password</label> 
                             <input type="password" 
                             id="upw" 
                             name="upw" 
                             placeholder="비밀번호를 입력하세요" 
                             class="form-control"> 
                         </div>
                         <span style="color:red;"><strong>{{ error }}</strong> </span>
                         <div class="row justify-content-center my-3 px-3"> <button class="btn-block btn-color" type="submit">Login</button> </div></form>
                         <div class="row justify-content-center my-2"> <a href="#"><small class="text-muted">Forgot Password?</small></a> </div>
                     </div>
                 </div>

                 <div class="bottom text-center mb-5">
                     <p href="#" class="sm-text mx-auto mb-3">Don't have an account?<a href="{% url 'signup'%}"><button class="btn btn-white ml-2">Create new</button></p></a>
                 </div>
                 
                
             </div>
             <div class="card card2">
                 <div class="my-auto mx-md-5 px-md-5 right">
                     <h3 class="text-white">Smart K-art에<br> 오신것을 환영합니다. :> </h3> <h6 class="text-white">Smart K-art는 똑똑한 소비자를 위한 똑똑한 계산형 장바구니 서비스입니다.<br> 충동구매와 과소비를 방지할수 있어요!</h6>
                 </div>
             </div>
         </div>
     </div>
 </div>
 {%endblock%}

Projects/Smart_Kart/FaceDetection/templates/FaceDetection/memo_list.html
{% extends "base.html" %}
{%block content%}

<style>
h6 {
    position: relative;
}

.icons {
    position: absolute;
    right: 5px
}




</style>

<div class="container px-4 py-5 mx-auto">
    <div class="card card0">       
        
        <div class = "mt-1 mb-4"><h3>- 쇼핑목록 - 
            <a class="icons" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                <i class='fas fa-plus fa-sm'></i>
            </a>
        </h3></div>

        
          <div class="collapse" id="collapseExample">
            <div class="card card-body">
                <form method="POST" action="{% url 'add_memo' %}">
                    {% csrf_token %} 
                    <div class="form-group">
                      <label for="id_mname">제목</label>
                      <input type="text" name="mname" style = text-align:center;>
                    </div>
                    <div class="form-group">
                        <label for="id_mdetail" rows="3">내용</label>
                        {% comment %}<input type="textarea" name="mdetail" rows ="3">{% endcomment %}
                        <textarea id="exampleFormControlTextarea1" rows="5" name="mdetail" style = text-align:center;></textarea> 
                    </div>
                   
                    <div class="form-group">
                        <label for="id_label">예산</label>
                        <input type="text" name="budget" style = text-align:center;>    
                    </div>
                


                    <div class="form-group form-check">
                        <label for="id_label">라벨</label>
                        {{ form.label }} 
                    </div>
                    <input type="hidden" name="uemail">

                    <button type="submit" class="btn btn-white ml-2">추가</button>
                  </form>
            </div>
          </div> 

            <div>
                {% for memo in memo_list %}
                    <div class = 'card-body'>
                        <h6><a href="/basketlist?todo_id={{memo.id}}">{{memo.mname}}</a>
                        <span class = "badge badge-{{memo.label}}">
                        {{memo.get_label_display}}
                        </span><br>
                        {{memo.cdate}}
                        <span class="icons">
                        <a href='#'><i class="fas fa-pencil-alt" style="color: orange;"></i></a>&nbsp;
                            
                            <a href="{% url 'finish-list-item' memo.id %}"><i class='fas fa-check'></i></a>&nbsp;
                            <a href="{% url 'delete-list-item' memo.id %}"><i class='fas fa-trash' style="color:red;"></i></a></span>
                        </h6>
                        
                    </div>
                    
                {% endfor %}
            </div>
        </div>

    <script>
        function button1_click(todo_id) {
            location.href = "/basketlist?todo_id="+todo_id; 
        }
    </script>

    </div>
</div>
{%endblock%}

Projects/Smart_Kart/FaceDetection/templates/FaceDetection/ocr.html
{% extends "base.html" %}
{%block content%}

<style>
h6 {
    position: relative;
}

.icons {
    position: absolute;
    right: 5px
}

</style>


<body>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-white ml-2" value="" upload> 이미지 업로드</button><br><br>
    {% if post %}
    <img src="{{ post.document.url }}" width = 350>
    <!-- <p>File uploaded at: <a href="{{ post.document.url }}">{{ post.document }}</a></p> -->
    <!--<p>contents: {{ ocrResult }}</p>-->
    <!-- <p>clean contents: {{ cleanResult }}</p> -->
    <!--<p><input type='text'  value={{ pdname }}></p>  textlist.0 -->
    <!--<p><input type='text' value={{ pdprice }}></p>-->
    {% endif %}
</form>
<br><br>
<form method='post' action='/add_item/'>
{% csrf_token %}
<!--{{ form.as_p }}-->
    <!--<button type="submit" class="save btn btn-default" value="" upload> 확인 </button>-->
    <p><input name='pdname' type='text'  value={{ pdname }}></p>
    <p><input name= 'pdprice' type='text' value={{ pdprice }}></p>
    <p><input name= 'todo_id' type='hidden' value={{ todo_id }}></p>
    <button type="submit" class='btn btn-white ml-2'>저장</button>
    <a href="{% url 'ocr' %}" class='btn btn-white ml-2' >다시찍기</a>
</form>

</body>
{%endblock%}